name: CMake build on OS X
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        brew install boost
    - name: Compile
      env:
        CXXFLAGS: -O2 -stdlib=libc++ -mmacosx-version-min=10.9
      run: |
        cmake .
        make -j 2
    - name: Test
      run: |
        ./test-suite/quantlib-test-suite --log_level=message
