name: CMake build on Windows
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        echo "::set-env name=BOOST_ROOT::$env:BOOST_ROOT_1_72_0"
        echo "::set-env name=BOOST_INCLUDEDIR::${{ env.BOOST_ROOT }}\boost\include"
        echo "::set-env name=BOOST_LIBRARYDIR::${{ env.BOOST_ROOT }}\lib"
    - name: Compile
      env:
        CXXFLAGS: -O2
      run: |
        cmake .
        cmake --build . --config Release
    - name: Test
      run: |
        .\test-suite\Release\quantlib-test-suite --log_level=message
